name: Tag Images

on: 
  workflow_dispatch:
    inputs:
      commitTag:
        description: 'Commit hash in cell'
        default: 'deadb33f'
        required: true
      keyword:
        description: 'Filter by keyword'
        default: '2021.3'
        required: true
      tagReplace:
        description: 'New tag to replace'
        default: '2021.3.X'
        required: true

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pip dependencies
        run: |
          docker image prune -a -f
          docker container prune -f

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Install pydoit fixed
        run: |
          git clone https://github.com/davidzyx/doit
          pip install ./doit
          rm -rf ./doit

      - name: Set Python-specific environment variables
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
          echo "PYTHONUNBUFFERED=TRUE" >> $GITHUB_ENV

      - name: Clone Wiki
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki

      - name: Tag Images
        run: >
          doit tag
          --commit_tag ${{ github.event.inputs.commitTag }}
          --keyword ${{ github.event.inputs.keyword }}
          --tag_replace ${{ github.event.inputs.tagReplace }}

      - name: Archive artifacts and logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: tag-artifacts
          path: |
            artifacts
